### ISSUE TITLE
Ambitious and seemingly unjustified statements on PIX

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#101]
**Section Number**
Section 5.1

**Issue**

The following statement does not seem to be justified:

>A primary use of the PIX Profile is to enable document consumers and document sources using the XDS Profile to find the patient’s identifier in that XDS Affinity Domain Patient Identifier Domain (XAD-PID).

Is this not too ambitious to say? An MPI can be also PIX based. I do not think that anywhere in the PIX profile spec it is claimed that its primary use is for the XDS profile. 

**Proposed Change** 

Either remove or clarify - substantiate this statement.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
The XDS profile did call upon PIX to do this role, and that is the dominant use of PIX.   PIX is an interoperability specification, as such an MPI is one implementation that might chose to use PIX as the interoperability layer. PIX does not dictate the policy for how cross-references are determined, only how to feed updates and how to query for cross-references.

I think the statement is correct and not ambitious.  @ivan-zapreev-work can you comment in light of my response?

**Comment by ivan-zapreev-work** [comment]
Well, for some one who does not know the history of PIX and XDS profile development reading: "A primary use of the PIX Profile is to enable document consumers and document sources using the XDS Profile" implies that PIX is developed for a certain specific purpose and is somehow tightly bound to XDS. The PIX supplement however says nothing about XDS. Thus stating that its main purpose is to be used with XDS is not substantiated enough. The way I see it, I may use PIX for whatever purpose I see applicable. Nothing limits me from doing this. ;)
