### ISSUE TITLE
The notion of Community is not defined in PIX profile

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#102]
**Section Number**
Section 5.1

**Issue**

Consider the next sentence:

>The PIX Profile can be used for Cross-Community if the communities are willing to have a centralized patient cross-reference

The community is not defined and its relation with an identification domain or issuing authority is not clear.

**Proposed Change** 

Please define what a community is and how it is related to an identification domain and an issuing authority.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
community is defined at the top of the HIE whitepaper. This is the context of the whole whitepaper.

**Comment by JohnMoehrke** [comment]
Remove the sentence. It is found at the end of the paragraph

A primary use of the PIX Profile is to enable document consumers and document sources using the XDS Profile to find the patient’s identifier in that XDS Affinity Domain Patient Identifier Domain (XAD-PID). Centralized Discovery and Retrieve are described above in Section 3.2. ~~The PIX Profile can be used for Cross-Community if the communities are willing to have a centralized patient cross-reference~~

**Comment by ivan-zapreev-work** [comment]
agreed
