### ISSUE TITLE
Some issues with concluding remarks on PIX profile

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#103]
**Section Number**
Section 5.1

**Issue**

Consider the next sentences:

>The Patient Identifier Cross-reference for Mobile (PIXm) provides the same query capability as PIX but leverages the FHIR standard. PIXm can be used as an API to a Patient Identity Management system like PIX defines. PIXm does not include a feed transaction, see the Patient Master Identity Registry (PMIR) discussion below.

I have two issues here:
1. I think that the statement in the first sentence is not sufficiently proven. For example: ITI-9 only returns the list of v2 patient identifiers - strings (with assigning authorities) ITI-83 returns FHIR Identifier resources and also the resource Links.
2. The last sentence does not seem to be correct. PIXm is PIX + FHIR façade allowing for the FHIR [ITI-83] transaction. So PIXm includes the feed transaction as it is part of the necessary PIX part of the PIXm. Therefore the link you make with PMIR here is not clear or well justified.

**Proposed Change** 

1. Consider substantiating the first statement or changing it to be more accurate
2. Consider removing the last statement or turning it into a more accurate one.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
1. I think the text is correct. If the PIXm is used as a front to PIX; then only identifiers will be returned, no Resource ids.
2. I think for the context of the paper, the link to PMIR is clear.

**Comment by JohnMoehrke** [comment]
change as below

The Patient Identifier Cross-reference for Mobile (PIXm) provides the ~~same query capability~~ **similar functionality** as PIX but leverages the FHIR standard. PIXm can be used as an API to a Patient Identity Management system like PIX **or PMIR** defines.  ~~PIXm  does not include a feed transaction, see the Patient Master Identity Registry (PMIR) discussion below.~~

**Comment by ivan-zapreev-work** [comment]
Looks good to me, thank you!
