### ISSUE TITLE
A seemingly unjustified statement in the PDQ profile description

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#104]
**Section Number**
Section 5.2

**Issue**

Consider the next sentences:

>The premise of this profile is that the PDQ service will be made available by systems with more comprehensive and more accurate demographic information about patients than other systems.
>A typical use of PDQ is to discover the patient's XDS Affinity Domain Patient ID.

I have two issues here:
1. I do not think that the first statement is justified. The profile itself does not pose any limitations or preconditions with that regard. Moreover, I do not see why a System potentiality allowing for a wider range of personal demographical data would not be allowed to query another system with less demographical data available, in case the first system just initially has very little information on the patient or the set of demographics of the second system is not a strict subset of that of the first one. So this statement here is in my opinion very arguable.
2. The second statement is also arguable. PDQ is not limited to be used just for discovering the XDS affinity domain. May be in your particular scope it is but not in general and you seem to make a generalized statement here.

**Proposed Change** 

Consider substantiating these statements or changing it to be more accurate.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
this is context within the HIE-Whitepaper; so within that context I think these statements are proper. I think they could possibly be improved.
