### ISSUE TITLE
A unclear formulation in the PDQ profile description

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#105]
**Section Number**
Section 5.2

**Issue**

Consider the next sentence:

>The PDQ service could be combined with the PIX service to provide comprehensive
patient identity knowledge.

What do you mean by comprehensive? How compulsory is this combination with PIX? Actually all the PDQ spec says on that is that in order to be able to return patient identifiers from other identification domains it is suggested that the Patient Demographics Supplier is grouped with the Patient Identifier Cross-reference Manager, but this is not a must.

**Proposed Change** 

Consider rephrasing.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
The statement is referring to the use of PIX feed to provide demographics/identifiers to a service that is allowing clients to query using PDQ or PIX.  Could be more clear.

**Comment by JohnMoehrke** [comment]
removed the sentence
