### ISSUE TITLE
A number of unsubstantiated or unclear statements in PDQ profile description

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#106]
**Section Number**
Section 5.2

**Issue**

Consider the next sentences:

>The Patient Demographics Query for Mobile (PDQm) Profile is functionally the same as PDQ but leverages the FHIR standard. PDQm can be used as an API to a Patient Identity Management system. PDQm can be a FHIR API backed by a PDQ query or a Cross-Enterprise Patient Discovery (XCPD) query.

1. The first sentence misses substantiation and does not seem to be solid. For example PDQ supports ITI-21 and ITI-22, PDQm on the other hand is just ITI-78, and this is without even going into the details on the actual transaction capabilities and available options.
2. In the second sentence: 
    1. What is a Patient Identity Management system? I do not think it has been defined
    2. I can not see a direct value of such a statement as in general it is a seems to be obvious one. In other words either it is trivial and there is no need for saying that or it is much deeper but then it has to be explained. (PIX, PIX, PDQ, PMIR and others) can also be used as a API to a patient identity management system
3. I can not quite agree with the last sentence, as:
    1. The capabilities of XCPD are way broader than those of PDQ or PDQm. PDQm allows for a tiny but of what XCPD allows for.
    2. I am not quite sure what you mean here. Is it not by definition that PDQm is supposed to provide a lightweight FHIR based API comparable to that of PDQ?

**Proposed Change** 

Consider rephrasing.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
1. the distinction is true, but unimportant in an HIE, and not often ever used. So we could change the wording to "similar" 
2. the use of "API" is indeed political. It is true the PDQ and PDQv3 can be argued as APIs. We should either explain "FHIR API" or drop  the use of "API" as too political
3. the point here is that an app that is just using FHIR, will use PDQm. Where the service side might need to reflect the queries into XCPD.  We are discussing high level things here, not technical details.
