### ISSUE TITLE
Some unclarity and potential imprecision in the PDQ profile description

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#108]
**Section Number**
Section 5.3

**Issue**

Consider the next sentence:

>XCPD is similar in function to PDQ but is used with the Federated Discovery and Retrieve model of Document Sharing.

Here I have two comments about:
1. I do not think this is a correct statement. PDQ allows for a small subset of functionality provided by XCPD
2. TO my knowledge, the XCPD profile does not limit its applicability to the Federated Discovery and Retrieve model of Document Sharing. In fact, XCPD does not have to be used in the context of document sharing.

**Proposed Change** 

Consider improving or substantiating the statement.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
I agree with the technical truth of the comments, but I am not clear on how correct it. Given that the whitepaper is focused on HIE, it is already a context constraint. This is not a whitepaper about each profile standing alone, it is about their role in and HIE.

@ivan-zapreev-work do you have a recommendation given my comment?

**Comment by ivan-zapreev-work** [comment]
Well, may be it is just worth stating that the considered profiles are not discussed in their full power but just in the narrower scope and thus the provided descriptions may be incomplete?

**Comment by JohnMoehrke** [comment]
I think I did say that.

**Comment by ivan-zapreev-work** [comment]
Ok, then it is resolved 👍
