### ISSUE TITLE
A statemen in PDQ profile description that does not seem to be relevant

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#109]
**Section Number**
Section 5.3

**Issue**

Consider the next sentence:

>XCPD supports a hierarchical approach which bridges communities that might use PIX or PDQ internally.

I do not see why is this important to be mention at this point. What the communities use internally is irrelevant to XCPD.

**Proposed Change** 

Consider omitting the last piece of the sentence: "that might use PIX or PDQ internally." or explain why it is important to mention.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
agreed
