### ISSUE TITLE
The notion of the "community based system" is undefined

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#110]
**Section Number**
Section 5.4

**Issue**

Consider the next sentence:

>The Patient Master Identity Registry PMIR Profile is a community based system of cooperating patient...

I am not sure what you mean by the "community based system"

**Proposed Change** 

Please re-phrase or define.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
I am not clear what a better concept would be. We are using the concept of a "Community" throughout the paper. PMIR is focused on being used and serving the needs of a community.
