### ISSUE TITLE
Figure 5.4-1: Patient Master Identity Registry flow is not explained that well

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#113]
**Section Number**
Section 5.4

**Issue**

Figure 5.4-1 does not seem to be explained that well:

1. The PMIR profile is not presented and it is not indicated how the components in the figure relate to the PMIR actors and ITI transactions. This is especially important because you use the PMIR actor names in the text after the figure
2. The elements of the Figure are not properly introduced, like what is "Patient Identity Manager", what does it do?
3. The Arrows marked with the (1), (2), and (3) are not explained in the text under the numerals but you use "First shown", 'Second shown", and "Third" without explicitly indicating you are talking about the Figure

**Proposed Change** 

1. Properly introduce the PMIR profile with its actors and transactions and show how they match with the elements in the Figure
2. Explain the components depicted on the diagram
3. Make sure you explain(1), (2), and (3) the interactions referring to the diagram by the corresponding numerals.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
This paper is not attempting to replace the details in PMIR. We expect that those interested in the details will click-thru to the details. That said, this diagram is not clear. We will work on the diagram and consider your points when doing so. The diagram needs to be higher-level than those found in the PMIR profile.
