### ISSUE TITLE
Multiple issues with the PMIR example explanations

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#115]
**Section Number**
Section 5.4

**Issue**

> First shown is the Data Services, representing any or all of the servers (e.g., EHR) in a community that hold data about patient subjects.

Sorry, I can not make sense of this sentence it feels like it is part of some other story.

> This Data Services uses the PMIR Patient Identity Subscriber to subscribe to be notified of any Patient Identity changes
(created, updated, merged, or deleted).

What is the meaning of the transaction (1) in Figure 5.4-1?  The same question holds for (2) and (3)

> This subscription triggers notifications later due to Registration Desk activities.

If (1) is the subscription to the Patient Identity Manager then why are there no depicted notifications sent to the Data Services in the Figure? Also note that the subscription mechanism is optional so I would not even mention it here.

> A patient presents, and is looked up in the Patient Master Registry. 

What do you mean by "A patient presents"? Is this the patient identity feed transaction [ITI-93]? If so then why are you saying that the patient is looked up in the Master Registry? That is not correct then as the Registry is not going to look things up for creating a new patient, if requested, it will just create it blindly.

> All updates are notified by the Patient Master Registry to any subscribing systems such as a Data Service.

This is not true as the subscription mechanism is optional.

> Third is the use of these Patient Identities in accessing or creating data in a Data Service.

Well, this is very odd, the interaction (3) does not connect to Data Services in any way. The formulation here is very unclear. I shall be expecting here an ITI-78 or ITI-83 kind transaction. The first one is about querying patient demographics and the second is about resolving the linked patient identifiers. None of this I can match with the text you put here...

**Proposed Change** 

Consider improving the text according to the comments.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
agreed improvement recommendations are good input

**Comment by JohnMoehrke** [comment]
removed the diagram and discussion about the diagram. We may chose to come up with a new diagram and explanation but this one could not be saved, and the previous diagrams were to detailed.
