### ISSUE TITLE
awkward MHD Push wording

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#116]
**Section Number** 

PUSH

**Issue** 

The current wording is very awkward and repeats "In addition the MHD can be used as an API in push mode. In this use case the MHD push request could be handled by an intermediary that further pushes the content using XDR or XDM. On the recipient side the MHD api could be used by an intermediary to forward a XDR or XDM push is further pushed to a Recipient using MHD; or the intermediary could store in a registry allowing a MHD Document Consumer to query and retrieve the content."

**Proposed Change** 

simplify

**Priority**:

low

**Comment by CharlesParisot** [comment]
John,

 

It distinguishes three cases and does not repeat at all.

Simply structure as three bullets:

 

"In addition, the MHD can be used as an API in push mode in various configuartions:

*	The MHD push request could be handled by an intermediary that further pushes the content using XDR or XDM. 
*	On the XDR or XDM recipient side of an intermediary, the MHD api could be used to forward a push to a Recipient using MHD; 
*	The MHD push request could be handled by an intermediary, that could store in an XDS registry/repository allowing via another intermediary an MHD Document Consumer to query and retrieve the content."

 

How does that feel ?

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : mardi 22 décembre 2020 14:02
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [IHE/HIE-Whitepaper] awkward MHD Push wording (#116)

 

Section Number

PUSH

Issue

The current wording is very awkward and repeats "In addition the MHD can be used as an API in push mode. In this use case the MHD push request could be handled by an intermediary that further pushes the content using XDR or XDM. On the recipient side the MHD api could be used by an intermediary to forward a XDR or XDM push is further pushed to a Recipient using MHD; or the intermediary could store in a registry allowing a MHD Document Consumer to query and retrieve the content."

Proposed Change

simplify

Priority:

low

**Comment by JohnMoehrke** [comment]
change paragraph to

In addition the [MHD](http://profiles.ihe.net/ITI/TF/Volume1/ch-33.html) can be used as an push API to a system that ultimately delivers the content. For example diagrammed below is MHD initiating a push to an Intermediary. In this use case the [MHD](http://profiles.ihe.net/ITI/TF/Volume1/ch-33.html) push request could be handled by the intermediary that further pushes the content using [XDR](http://profiles.ihe.net/ITI/TF/Volume1/ch-15.html) or an e-mail carrying [XDM](http://profiles.ihe.net/ITI/TF/Volume1/ch-16.html) (e.g., the Direct Project). On the recipient side (not shown in the diagram) the [MHD](http://profiles.ihe.net/ITI/TF/Volume1/ch-33.html) could be used by an intermediary to forward a [XDR](http://profiles.ihe.net/ITI/TF/Volume1/ch-15.html) or [XDM](http://profiles.ihe.net/ITI/TF/Volume1/ch-16.html) push content. MHD (not shown in the diagram) could also be used on the recipient side as a query/retrieve where the intermediary has cached content addressed to that recipient. This Intermediary is an example of a Direct Project HISP with the added functionality provided by MHD, enabling FHIR based push with end-to-end interoperability between three different transport stacks in MHD, XDR, and e-mail XDM.
