### ISSUE TITLE
References

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/HIE-Whitepaper#117]
**Section Number** *1.4*

**Issue** *the last sentence of this paragraph says: "Including USA, Europe, and Japan, and the world." i don't understand the "and the World" with the  reference to the connectathon web page where it is written that ihe connecthatons are held in usa europe and japan..*

**Proposed Change** *change the last sentence in "Including USA, Europe, and Japan."*

**Priority**:low

**Comment by JohnMoehrke** [comment]
The intention of the "around the world" was to show that we are inclusive, and specifically we do have  Projectathons in many locations. Is the "around the world" really important to remove? Is the clarity I give here really necessary to explain?

**Comment by CharlesParisot** [comment]
I would not remove, this is an important strength of IHE that need to be proudly stated.

 

De : John Moehrke <notifications@github.com> 
Envoyé : mercredi 10 février 2021 11:05
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] References (#117)

 

The intention of the "around the world" was to show that we are inclusive, and specifically we do have Projectathons in many locations. Is the "around the world" really important to remove? Is the clarity I give here really necessary to explain?

**Comment by JohnMoehrke** [comment]
Change to:
 IHE Connectathons take place multiple times and locations annually around the world to advance health IT and patient safety, including USA, Europe, and Japan, and elsewhere.

fix the IHE-USA link, it is broken. just use https://www.iheusa.org/

**Comment by gregoriocanal** [comment]
i still think that there is something strange...
we are saying IHE Connecthatons are held in usa europe and japan and elsewer in the world.. but if you click on the link () the web page lists only europe usa and japan

could we say: IHE Connectathons take place multiple times and locations annually around the world to advance health IT and patient safety.
?
