### ISSUE TITLE
add figure to section 2.6

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/HIE-Whitepaper#118]
**Section Number** *2.6*

**Issue** *I will found usefull if in this section we will add Figure 4.1.3.1-1: of IHE ITI TF vol3*

**Proposed Change** *

**Priority**:low

**Comment by JohnMoehrke** [comment]
The recommended figure is https://profiles.ihe.net/ITI/TF/Volume3/media/Figure_4.1.3.1-1.png
seems useful.

I wonder if we can just use the image as published there, while displaying it in the whitepaper? This should be possible like this

```
![](https://profiles.ihe.net/ITI/TF/Volume3/media/Figure_4.1.3.1-1.png)
```

**Comment by CharlesParisot** [comment]
Yes, very important figure.  Keep as is.

 

De : John Moehrke <notifications@github.com> 
Envoyé : mercredi 10 février 2021 11:10
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] add figure to section 2.6 (#118)

 

The recommended figure is https://profiles.ihe.net/ITI/TF/Volume3/media/Figure_4.1.3.1-1.png
seems useful.

I wonder if we can just use the image as published there, while displaying it in the whitepaper? This should be possible like this

![](https://profiles.ihe.net/ITI/TF/Volume3/media/Figure_4.1.3.1-1.png)
