### ISSUE TITLE
enhance Figure 3-3 

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/HIE-Whitepaper#119]
**Section Number** *Figure 3-3:*

**Issue** *In the picture it seems that MHD consumer and XDS consumer can only query/retrieve in their community. also the test below does not explain how thay can search or retrive for document in other communities. the text it is focused on pubblication but XCA it is just for search and retrieve*

**Proposed Change** *update the figure to make clear how a consumer can access a document in another community (maybe simply changing the arrow's color or pointing directly to the other communities) and briefly explain the mechanism in the text below*

**Priority**: medium

**Comment by JohnMoehrke** [comment]
I agree this is very confusing diagram. not sure the best new image. Might it be bad to just remove it?

**Comment by JohnMoehrke** [comment]
using new diagram, fixed up. Remove publication, and make more clearly XCA centered
