### ISSUE TITLE
Notifications references

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/HIE-Whitepaper#120]
**Section Number** *3.2.4 *

**Issue** *the text talks about push and pull style for notifcations and in the end of the section there is a reference to DSUB. Bu this reference points just to normative text, thus only for Push-style.*

**Proposed Change** *add a reference for DSUB extension where it is explained the pull-style notification*

**Priority**:medium

**Comment by JohnMoehrke** [comment]
Can you suggest specific text? I don't know DSUB.

**Comment by gregoriocanal** [comment]
i suggest to replace the two bullet points:

- Using a push-style method of notification where the Subscriber subscribes to receive notifications about the availability of documents based on specific criteria (see ITI TF Vol 1 )
or

- Using a pull-style method which creates a Pull Point resource able to store notifications targeted to a specific recipient. Notifications stored in the Pull Point can be retrieved using a specific transaction (see ITI TI Extensions to Document Metadata Subscription ).

**Comment by gregoriocanal** [comment]
note that the Pubblicaton and Discovery slide deck talks just about push style notification

**Comment by JohnMoehrke** [comment]
I think we only have DSUB now days. I suspect the text is a left over from the NAV days. We no longer have NAV, so that should be cleaned up.

**Comment by JohnMoehrke** [comment]
updated the text to use the actor names. The link to DSUB needs to be just to the DSUB. We can't include a direct link to the supplement or will need to revise the whitepaper when that supplement becomes final. But the DSUB profile pointed to does reference the extension supplement. When the reader does not find the pull point actors, they should be able to understand to go to the supplement.
