### ISSUE TITLE
which infrastructure should i choose?

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/HIE-Whitepaper#121]
**Section Number** *3.4*

**Issue** * i found a discrepancy between the figure and the text below. The figure seems to say add MHD to XDS or XCA infrastracture but the text it says "Where none of these conditions exist, then the choice could be XDS or MHDS based" but in the figure above if no infrastructure points only to MHDS*

**Proposed Change** *If we want them to use MJHD or MHDS henge the text otherwise the figure should be changed according to the fact that if i have no infrastucture at all i can choose an XDS infrastructure*

**Priority**: low

**Comment by JohnMoehrke** [comment]
the diagram is bias... it was initially to help those focused on FHIR... where as those that don't care about FHIR should still feel that XDS and XCA are recommended.

new diagram needs to make this clear.

**Comment by JohnMoehrke** [comment]
updated on call today
