### ISSUE TITLE
Figure 4-1: mXDE wrong placeholder?

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/HIE-Whitepaper#122]
**Section Number** *Figure 4-1: mXDE*

**Issue** * I think that in figure numbers 1 2 3 and 4 are not aligned with the list below.. number 1 in the list should be what it is pointed with 2 in figure , 2 should be 3 and 3 should be 4. I dont' know what should be number 4 in list and 1 in figure*

**Proposed Change** **

**Priority**: medium

**Comment by JohnMoehrke** [comment]
correct. The numbers were for a different diagram. The numbers are not explaining the events
1. Documents are published into a Document Sharing infrastructure
2. Specific data elements are extracted from the structured documents per the mXDE Profile.
3. Data elements (e.g., allergies) queried using the FHIR based Query for Existing Data for Mobile (QEDm) Profile.
4. Each data element is linked to the document(s) from which it was extracted per the mXDE Profile. Clinician accesses context of any data element of interest using source documents (XDS, MHD Profiles) providing the clinical context in which the observation was recorded.
