### ISSUE TITLE
Add reference to case study from Sequoia

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#18]
provide links to some HIE case studies known to Sequoia Project

**Comment by JohnMoehrke** [comment]
@dididavis has there been any progress on publishing, or gathering existing published, case-studies on how Sequoia Projects utilize the IHE Document Sharing profiles?

**Comment by JohnMoehrke** [comment]
@dididavis have you found a sequoia published paper on their use of IHE profiles that we can point at?

**Comment by dididavis** [comment]
@JohnMoehrke, unfortunately I don't have a good link for you yet.  I know there is work underway, but I don't find anything officially published at this moment.  I have reached out to my marketing department and will keep you posted.

**Comment by JohnMoehrke** [comment]
@dididavis any update on getting us a Sequoia paper on their use of Document Sharing profiles?
