### ISSUE TITLE
Pick a html style from the github choices

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#20]
GitHub enables us to use theme for these projects. The theme mechanics they support is documented here
https://help.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-with-the-theme-chooser 

I think we should first look at the pre-canned theme choices. I like minimal. We can always change that decision later, but it seems we need to chose something. I see jekyll mentioned, which I understand is an html rendering engine, and one the HL7 IG publisher uses... so future we might be able to get creative.

Publications workgroup is looking at the alternatives. HIE-Whitepaper will be a good experiment.

**Comment by JohnMoehrke** [comment]
Discussed on call July 6th: 
* themes available may be not well managed. @vassilpeytchev noted that the github where the themes are managed has not been touched in many years.
* We might need to import a theme that is close, and manage it ourselves. We would need someone that is willing to do that onbehalf of all IHE projects that would use markdown in github for editing a publication. 
  * https://docs.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll
* note that ITI has three whitepapers looking at this, and one profile (IUA) - so there is some need. However the base html output from github with markdown may be sufficient for our publication needs. We could chose to just handle style on the official IHE web site publication with CSS, and not with jenkins. right?

Need to decide if we use one of these themes in the short term, delaying efforts to customize. Or if we don't use a theme at all.

**Comment by JohnMoehrke** [comment]
This week the ITI committee looked at a few of the themes. We decided to first publish with
    theme: jekyll-theme-slate

as it seems the cleanest, has wider text, and seems to work for now.

We can enhance these themes over time.

**Comment by JohnMoehrke** [comment]
@MaryLJ should we decide that for now we stick with the the current pages theme? We can always improve it later... and I don't think there is time or resources to create jekyll code... right?

**Comment by MaryLJ** [comment]
Yes, I agree.

**Comment by JohnMoehrke** [comment]
seemed that today we might have agreed to abandon these themes and just publish the unpolished html? Seems the theme was getting in our way more than it was helping.  right?

**Comment by GumptionWare** [comment]
This is something that can be readily changed later. If it is getting in the way of updating the content, there is no harm in going without a theme and revisiting later.

**Comment by JohnMoehrke** [comment]
agreed September 15th meeting to remove theme
