### ISSUE TITLE
Describe CDA vs FHIR documents

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#23]
FHIR document is a flat set of resources. Import into a system is implied as merging the resources into that system (Create/Update).  Meaning that once digested it is available as FHIR resources.  May still need the FHIR Document need to be persisted as Binary.

Note this is not unlike mXDE / QEDm mechanics defined for CDA-> FHIR service

these are more driven by tooling, where a reference FHIR Server comes instrumented for treating an import of a FHIR Document as a request to import the resources.

is sending a FHIR Document so easy to import that a sender should expect it will be imported?

add text to Distinction between Documents and Messages

**Comment by GumptionWare** [comment]
Notes to self:
- Great reference: https://1up.health/blog/post/2018-01-15-fhir-vs-cda/

**Comment by CharlesParisot** [comment]
This reference is a very weak analysis and omits several critical elements in the discussion.
The main one being the source attestation, which is much simpler to address in CDA than in FHIR and the creation of trusted set of data for a patient that has been cured by a physician.

These can be done in FHIR documents, but much more brittle, and deployment dependent.

Charles

**Comment by GumptionWare** [comment]
Thanks, @CharlesParisot. That was a "getting started" reference (a reminder to me--in addition to notes in this comment thread) to start building the actual content we need. I appreciate your suggestions, and I look forward to your feedback on the text I draft.

**Comment by JohnMoehrke** [comment]
see if the new section on CDA vs FHIR added addresses this?

**Comment by GumptionWare** [comment]
It does seem to--especially at a very high level, which seems appropriate for this document.

- **Process question**: What is our rubric (as we evolve this process) for when and how to include references to "dig deeper." Obviously, there is a ton of more detailed information elsewhere about both CDA/C-CDA and FHIR. What is your thought process about conventions for "see more here" references?
