### ISSUE TITLE
more natural links to resources (e.g. white paper or profile) when that is what narrative needs. Rather than using #further-reading secondary stop

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#29]

**Comment by GumptionWare** [comment]
Editing now, and I'm noticing that a convention seems to be that every occurrence of a referencable term or acronym (like "XDS") repeats the link to the underlying document.

Until we decide otherwise, I will continue following this convention.

**Comment by GumptionWare** [comment]
Editing completed; pull request created.

**Comment by JohnMoehrke** [comment]
not done yet. see requests in the pull-request
