### ISSUE TITLE
update Content Creator/Consumer diagram to new version from PCC.

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#31]

**Comment by MaryLJ** [comment]
See CP-PCC-0211 in this Google Drive folder https://drive.google.com/drive/folders/119r4iNYjXNESdUqNSOq8HfkmPerEUlFL

**Comment by JohnMoehrke** [comment]
is this now in the current supplement template?

**Comment by MaryLJ** [comment]
No, but a new version is in the works.

**Comment by JohnMoehrke** [comment]
excellent

**Comment by JohnMoehrke** [comment]
Updated diagram. source is available in UML, removed PPTX as unnecessary.
