### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by MaryLJ** [IHE/HIE-Whitepaper#48]
There are some broken links. See example below. I think a # is needed in front of the section that link is pointing to (e.g., principles-of-health-document-sharing)
<h3 id="323-governance">3.2.3 Governance</h3>

<p>As described in <a href="https://ihe.github.io/HIE-Whitepaper/principles-of-health-document-sharing">Principles of Health Document Sharing</a> 
is document content neutral; uses
document metadata that are represented in a structured, standard format;
and supports longevity of document storage.</p>

**Comment by JohnMoehrke** [comment]
good catch. Some were missing the #

fixed... again.
