### ISSUE TITLE
Define and document the public comment process

### ISSUE THREAD

**Issue by MaryLJ** [IHE/HIE-Whitepaper#49]
The public comment process should be defined and documented.

**Comment by JohnMoehrke** [comment]
Write up process as a wiki article:

Discussed September 1 https://github.com/IHE/HIE-Whitepaper/wiki/September-1,-2020
Decided that PDF is not necessary, so will **only publish in html**. Most users understand their browser can produce PDF.
Decided to give reviewer alternatives of github issues (if they are comfortable), or the classic IHE comment form. #51

**Comment by JohnMoehrke** [comment]
need to determine markdown to html rendering. Today using github pages which has a unique rendering. Tried pandoc but don't get consistent table rendering.

**Comment by JohnMoehrke** [comment]
discussed today comment submission. some concern that providing too many ways for comments to be submitted will lead to overhead. Some concern that large organizations need ability to submit bulk comments (spreadsheet). 
Decided to continue to allow all comment methods. 
Likely will resolve comments using github issues, but will need to determine that once we get comments in.

**Comment by JohnMoehrke** [comment]
see http://profiles.ihe.net/ITI/HIE-Whitepaper/index.html as the link we will use for public comment

I have not yet figured out how to get portable html rendering that is consistent with the html rendering we get from github https://ihe.github.io/HIE-Whitepaper/

**Comment by JohnMoehrke** [comment]
get google form for issue submission so that anonymous users can submit comments and they go directly into github issues.

**Comment by JohnMoehrke** [comment]
the ihe.github.io could point at this whitepaper (https://ihe.github.io/)

**Comment by JohnMoehrke** [comment]
done
https://github.com/IHE/publications/wiki/Authoring-long-form-Supplements-and-Whitepapers
