### ISSUE TITLE
introduction paragraph for Swiss case study

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#54]
section 7.1.6 is placed to hold a quick introduction to the Swiss use of Document Sharing. There is a link to a page, but no introduction text. Also what would be the best link or set of links?

**Comment by JohnMoehrke** [comment]
is this a better link?  https://www.ihe-suisse.ch/de/aktuell/blog/ihe-profile-als-kern-des-elektronischen-patientendossiers/

**Comment by msmock** [comment]
Dear John

yes, this is better link, but currently the text is german and french only.

There is also an overview figure which shows all IHE ITI actors used in the Swiss EPR with URL https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/E/overview-profiles-swiss-electronic-patient-record.pdf <https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/E/overview-profiles-swiss-electronic-patient-record.pdf> 

Info on the Swiss EPR projectathon (each year in September) is available on this side 
https://www.e-health-suisse.ch/en/technik-semantik/epr-projectathon/general-information.html <https://www.e-health-suisse.ch/en/technik-semantik/epr-projectathon/general-information.html> 

A link collection with the references to all technical specifications used in the EPR context including the IHE ITI is placed on this page: https://www.e-health-suisse.ch/en/technik-semantik/epr-projectathon/epr-programming-aids/relevant-specifications.html <https://www.e-health-suisse.ch/en/technik-semantik/epr-projectathon/epr-programming-aids/relevant-specifications.html> 

We already decided to produce a whitepaper which will fit your needs, but we didn’t start to work on it yet. 

Regards
Martin

**Comment by JohnMoehrke** [comment]
@msmock I would be happy if you submit a proposed text. The comment you submitted could be re-stated for the proposed text. When a new whitepaper comes up, it can replace it.

**Comment by msmock** [comment]
Dear John

I’ll start to work on that when re-arriving from holidays at Oktober 19. 

Regards 
Martin

**Comment by JohnMoehrke** [comment]
Note that pointing at an article(s) that is only in swiss friendly language is fine. We just need a paragraph in the HIE-whitepaper that is in English and introduces the article(s). @msmock @oliveregger
