### ISSUE TITLE
add link to HIMSS healthcare interoperability paper

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#59]
https://www.himss.org/resources/interoperability-healthcare

**Comment by JohnMoehrke** [comment]
@a3vedi can we get this paper updated with a bit more text around their bullet on "IHE"? It seems under explained relative to the peers in that bullet list.

**Comment by a3vedi** [comment]
Sure John, will do. That's on me. ;)  Our team is meeting with the group to refresh that info and will update with more text. Let me know if you have specific text or points in mind.
