### ISSUE TITLE
remove references to NAV

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#7]

**Comment by GumptionWare** [comment]
I see two references to NAV. Im guessing we are removing these because NAV is retired. Should there be a reference to a replacement profile?

**Comment by JohnMoehrke** [comment]
yes. NAV no longer exists.

John Moehrke 🔥 Architect: Healthcare Informatics Standards -
Interoperability, Privacy, and Security
IHE Co-Chair IT Infrastructure Planning and Technical
HL7 Co-Chair Security WG, FHIR FMG, FHIR facilitator, and FHIR Foundation
founding member
Employee of ByLight Professional IT Services -- Contractor to VHA
MyHealtheVet
JohnMoehrke@gmail.com  |  M +1 920-564-2067  |  John.Moehrke@bylight.com
 https://healthcaresecprivacy.blogspot.com
