### ISSUE TITLE
do we publish for public comment or just publish?

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#72]
Given that this is a whitepaper, it does not need to go to a public comment. We have not had much success at getting comments on whitepapers. So, recommend we choose to simply publish it, with the given statements already in the text about how to submit issues.

**Comment by CharlesParisot** [comment]
There may an other strategy that requires a little more work, but that will ensure visibility for the white paper.

Run public comment as the white paper is promoted to the various national deployment Committees.  Even if you get only 30 people commenting, these will know that the WP exists !

Charles

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : John Moehrke <notifications@github.com>
Envoyé : Monday, October 26, 2020 7:39:23 PM
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [IHE/HIE-Whitepaper] do we publish for public comment or just publish? (#72)


Given that this is a whitepaper, it does not need to go to a public comment. We have not had much success at getting comments on whitepapers. So, recommend we choose to simply publish it, with the given statements already in the text about how to submit issues.

**Comment by JohnMoehrke** [comment]
discussion on the call today:
* The typical process for publication vs public-comment is the same, so there is not an advantage of a public comment
* However, publication and notification for public-comment is not much of a burden
* The main burden is that the ITI Tech committee would need to reserve some winter capacity to resolve comments. We could choose to not reserve capacity given that we don't expect much comment and could process the comments as a background task.
* A public comment is easier for some committee members to promote to others as a reason for the others to review. Where as a simple publication might not be seen as useful to read.
* The content of the paper is 80% from the current paper so we don't expect much comment
* To public comment would mean there would be some indication on the paper that it is in public comment, in addition to the listing on the public comment page.
* This indication in the paper should be the pre-text to the existing text inviting comments. The text following the table of contents,.

**Comment by JohnMoehrke** [comment]
seem the running conclusion is that a public comment notification would be helpful for promotion, while expecting no comments. Thus the overhead this winter is simply mechanics to update the status and publish. Thus two promotion campaigns. No reserved capacity in the winter quarter.
