### ISSUE TITLE
1.2 Intended Audience Details

### ISSUE THREAD

**Issue by AdamBazer** [IHE/HIE-Whitepaper#74]
Can we specify some example worksites and work roles that we are targeting this whitepaper towards?

**Comment by JohnMoehrke** [comment]
Im sure we can... but I don't know what a "work role" is... I presume this is buzzword speak for making the audience clear? so, feel free to propose the text you want to add and the location to add it.

**Comment by AdamBazer** [comment]
John,

Do the following work sites and work roles define the orgs and people that will be the audience for this whitepaper:

Work Sites
Health Information Exchanges
Health Systems
Ambulatory Clinics

Work Roles
CIO
CMIO
CNIO
CISO

Thanks for your insights, John!

With Respect,
[https://image.emailhimss.org/lib/fe3a117171640479771772/m/1/e3a100b6-5b49-4226-942e-9fc8edd21ff4.png]

Adam Bazer, MPD
Senior Technical Manager, Informatics & HIT Standards
33 West Monroe Street Suite 1700 Chicago IL 60603
T  312.915.9257  |  E  Adam.Bazer@himss.org<mailto:Adam.Bazer@himss.org>
L Connect on Linkedin<https://www.linkedin.com/in/adambazer/> | T Follow on Twitter<https://twitter.com/adambazer?lang=en>

**Comment by JohnMoehrke** [comment]
Those seem like they should be considered our audience. I am just not sure that is the only audience. The paper is not really intended for technical implementers, or end-users.. I just don't know what other audience types to choose from.

**Comment by AdamBazer** [comment]
Well, this is a fun onion to keep peeling ☺

Is this paper to help educate the people/orgs that will dictate the actions taken by technical implementers or end-users as it relates to Health Information Exchange?

It seems we are trying to influence the decision makers vs. educate the implementers.  That the function of the whitepaper is to provide the background knowledge decision makers will need to make the governance and policy-related decisions that will impact the successful implementation of these IHE integration profiles focused in HIE.

Is this list more accurate?  Anyone on here that shouldn’t be?

Work Sites
Govt
Federal Health Agencies (ONC, HHS, NIST)
Regional/State Health Agencies (State Public Health Agencies)

NGOs
Health Information Exchanges
Standards Development Organizations
HIT Non-Profits/Professional Associations (GDHP, HIMSS, etc.)

Clinical
Health Systems
Ambulatory Clinics
Long-term, Post-Acute Care

Work Roles
CEO
CIO
CMIO
CNIO

Are we getting closer or farther away from the optimal audience to turn this education we are providing into action?

Thanks for your insights, John!

With Respect,
[https://image.emailhimss.org/lib/fe3a117171640479771772/m/1/e3a100b6-5b49-4226-942e-9fc8edd21ff4.png]

Adam Bazer, MPD
Senior Technical Manager, Informatics & HIT Standards
33 West Monroe Street Suite 1700 Chicago IL 60603
T  312.915.9257  |  E  Adam.Bazer@himss.org<mailto:Adam.Bazer@himss.org>
L Connect on Linkedin<https://www.linkedin.com/in/adambazer/> | T Follow on Twitter<https://twitter.com/adambazer?lang=en>

**Comment by JohnMoehrke** [comment]
@AdamBazer are you happy with this set of audience? How do you see these getting put into the text?

**Comment by JohnMoehrke** [comment]
- Govt (MOH, CDC)
- Federal Health Agencies (ONC, HHS, NIST)
- Regional/State Health Agencies (State Public Health Agencies)
- NGOs  (WHO, UNICEF)
- Health Information Exchanges
- Standards Development Organizations
- HIT Non-Profits/Professional Associations (GDHP, HIMSS, RSNA, etc.)
- Health Systems
- Ambulatory Clinics
- Long-term, Post-Acute Care
- Executive Offices: CEO, CIO, CMIO, CNIO, CSO, CTO, CPO, C3PO, etc

**Comment by AdamBazer** [comment]
John,

Thanks for the updated list.  It really helps fill in who we are targeting with this thought leadership content.

Have a great weekend!

With Respect,
[https://image.emailhimss.org/lib/fe3a117171640479771772/m/1/e3a100b6-5b49-4226-942e-9fc8edd21ff4.png]

Adam Bazer, MPD
Senior Technical Manager, Informatics & HIT Standards
33 West Monroe Street Suite 1700 Chicago IL 60603
T  312.915.9257  |  E  Adam.Bazer@himss.org<mailto:Adam.Bazer@himss.org>
L Connect on Linkedin<https://www.linkedin.com/in/adambazer/> | T Follow on Twitter<https://twitter.com/adambazer?lang=en>
