### ISSUE TITLE
Should we have a section on IHE-Connectathon and Projectathon benefit for HIEs?

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#76]
New section?

**Comment by JohnMoehrke** [comment]
@dididavis did you get time to put into this? How can I help?

**Comment by dididavis** [comment]
The text you added reads well except the second and third bullet point formatting... second bullet read including: and I would think the third bullet would be indented?  Also, any way to add the graphic from slide #3 in the PPT I sent to break up all the words....I think it is a nice addition as a visual.
