### ISSUE TITLE
Link to HL7 Structured Documents Section 1.2 Broken

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/HIE-Whitepaper#77]
Section 2.3 of the whitepaper begins with a link to "The HL7 standard for Structured Documents Section 1.2 ".  This link does not appear to resolve.

**Comment by JohnMoehrke** [comment]
@keithboone can you help us with a link to the document properties? It is not clear where CDA core is published openly. It is published in a ZIP - https://www.hl7.org/implement/standards/product_brief.cfm?product_id=7 - is that the best we can hope for?

**Comment by JohnMoehrke** [comment]
With no solution forthcoming. I recommend we just remove the link, leaving the text as is.
