### ISSUE TITLE
The origin of the columns and their content in Table 5-1 is not clear

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#88]
**Section Number**
Section 5

**Issue**
The "Assumptions" and "Conditions" columns of the table seem very controversial to me:
1. What is the difference between the assumptions and conditions? Both sound like more or less the same.
2. Where does the data placed in these columns come from? I see there multiple statements that are not reflected back in the standards, i.e. the IHE profile supplements these are not stated as required pre-conditions.
3. The points in the "Conditions" column are often not related to interoperability but are subject to internal implementation. Thus, according to your ow definitions, they do not have anything to do with the IHE profiles. So the question is then why do you mention such points? An example is: "The consumers of cross-references between identities from different identity domains either persist the cross-reference and actively process update notifications (profile option), or never persist cross-references and re-query when needed."

**Proposed Change** 

1. Clearly explain the distinction between the "Assumptions" and "Conditions"
2. Properly cite and reference the specifications or other documents to support the statements placed in the "Assumptions" and "Conditions" columns.
3. Either explain why you list implementation specific items in this column or consider removing them as irrelevant.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
I understand the concern. However I think this concern is beyond the scope of a whitepaper. This is not a specification that would be expected to have strong linkage for everything said. As a whitepaper it does speak to the implementer and deployment. This said, we should be more clear. So I expect there is some thing that can be done to clean it up.

**Comment by JohnMoehrke** [comment]
@CharlesParisot what was your distinction between Assumptions and Conditions? Can you provide guidance?
