### ISSUE TITLE
The meaning of "Deployment time" is unclear

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#89]
**Section Number**
Section 5

**Issue**

> The process to create and update the registry of identities along with their demographics needs to be addressed at deployment time for each one of the identity domains served.

Here and in multiple other places in Table 5-1 once you mention "deployment time" you seem to mean something other then a regular notion of deployment. The common notion just assumes a piece of software being installed and started on a particular computational resource. What you seem to mean with deployment is the setting up/configuring the entire system.

**Proposed Change** 

Please make it very clear - add a definition - of what you mean by "deployment".

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
Good observation. We likely need to address the distinction between writing software to be used in many settings, a community defining their community specific constraints, customizing general software for the specific community constraints, deployment of this to real-world use, and continual use of a system as intended.

I am not sure we have good words for these, or if these are the right phases.  We do talk to each of these, and have various whitepapers and handbooks to guide... but this has not been deeply described in the HIE-Whitepaper as it is trying to address high-level concepts, it is not trying to address programming, project based customization, deployment, or day-to-day. It does need to use these phases in a clear way, so I do understand a need to add clarity. It just seemed the terms we were using were clear.

@ivan-zapreev-work what is meaning of deployment that we need to distinguish from?
