### ISSUE TITLE
Review DSUB text is still current thinking on DSUB

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#9]
DSUB has changed in the last 8 years, so this text might need updating.

Ask to @mzanardini that the text be reviewed and any alternations be recommended. This recommendation can be via email, updating this issue, or pull-request

**Comment by DavidPyke** [comment]
The new text is roughly the same but outlines the options:
DSUB describes the use of subscription and notification mechanisms for use within an XDS Affinity Domain and across communities. The subscription allows for the matching of metadata during the publication of a new document for a given patient, and results a notification which can be parsed:  
1. Using a push-style method of notification where the Subscriber subscribes to receive notifications about the availability of documents based on specific criteria or, 
2.	Using a pull-style method which creates a Pull Point resource able to store notifications targeted to a specific recipient. Notifications stored in the Pull Point can be retrieved using a specific transaction.

**Comment by JohnMoehrke** [comment]
will you create a pull request with your recommended updates to the text? What you describe is likely how DSUB changed from the original write of the HIE whitepaper to now days.

**Comment by JohnMoehrke** [comment]
@DavidPyke did your ***merged*** **pull request** address this issue?  https://github.com/IHE/HIE-Whitepaper/pull/58

**Comment by DavidPyke** [comment]
I believe so but I didn't open the issue so I didn't close it.

**Comment by JohnMoehrke** [comment]
we will review on our call tuesday
