### ISSUE TITLE
Issues with PDQ Assumption 2.

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#90]
**Section Number**
Section 5

**Issue**

In Table 5-1:

> 2. It supports the ability to query in one or more patient identity domains of interest, by a set of demographics traits and get in response one or more matching identities with their complete set of demographics traits, usually including patient identifiers.

Here I see two issues:
1. "query in one or more patient identity domains of interest" to my knowledge the query is always done for a single domain, the one that the application belongs do;
2. "usually including patient identifiers." - to my knowledge the identifiers are always included in the response, one can choose to get the other domains as well (for all known or selected subset of other domains);

**Proposed Change** 

1. Check the PDQ spec on the issues above
2. Consider removing/changing "or more patient identity domains of interest" and "usually including patient identifiers."

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
I agree we can simplify, but I think the text is not wrong. This is a whitepaper explaining trends,, it is not a specification.

**Comment by ivan-zapreev-work** [comment]
I agree with you comment, however, I believe that if the information placed in the White Papaer contradicts the specification then it is at least missleading.

**Comment by JohnMoehrke** [comment]
I don't think there is any restriction on #1. The server side could be representing many domains, as is commonly done in an HIE.  @CharlesParisot is this correct?

**Comment by CharlesParisot** [comment]
John,

 

In proposed changes on  <https://github.com/IHE/HIE-Whitepaper/issues/1> #1, I see an issue with the current text about making the claim that MHDS supports distributed repositories without a repository Actor, or without a combines source/repository Actor.

This is a non-substantiated claim, as it violates IHE principles of Actor and Transactions.  Introducing such a topic of discussions here creates obscure and confusing text for 98% of the readers, as shown below in the green text:

[XDS](http://profiles.ihe.net/ITI/TF/Volume1/ch-10.html) minimizes the burden imposed on the document sources

when sharing documents by establishing the use of two infrastructure

components (the document registry and document repositories), which

handle most of the effort involved in exchanging clinical data. This

separation allows for minimal yet rich metadata to be centrally managed

in a document registry while the full clinical details stay protected

within distributed document repositories.

[MHDS]( <http://profiles.ihe.net/ITI/TF/Volume1/ch-50.html> http://profiles.ihe.net/ITI/TF/Volume1/ch-50.html) allows for a similar separation of repository, but does not call out the repository actor. The MHD Document Source simply preserves the document in an appropriate repository available to the MHDS community, and records the URL to that location when publishing the metadata to the MHDS repository. The MHD Document Source can include the document within the publication request where the MHDS Registry will store and provide access to it centrally.

 

The rest of the text looks fine.

Thanks

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : jeudi 11 février 2021 08:10
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Charles Parisot <charles@interopehealth.com>; Mention <mention@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] Issues with PDQ Assumption 2. (#90)

 

I don't think there is any restriction on #1 <https://github.com/IHE/HIE-Whitepaper/issues/1> . The server side could be representing many domains, as is commonly done in an HIE. @CharlesParisot <https://github.com/CharlesParisot>  is this correct?

**Comment by JohnMoehrke** [comment]
@CharlesParisot this issue is about PDQ. Not about MHD or MHDS.
