### ISSUE TITLE
XCPD profile functionality seems to be missing

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#91]
**Section Number**
Section 5

**Issue**

In Table 5-1:

> It supports the ability to query by a set of demographics traits, including a domain-specific patient identifier, and get in response one or more matching identities with a complete set of demographics traits, and usually the patient identifier from the remote patient identity domains.

This is not the only thing XCPD allows for it also allows to:
1. Communicate the demographics with the caller domain patient id to the called domain
2. Query the domain for the other domains having the information on a particular patient.

**Proposed Change** 
Make sure that the XCPD profile functionality description is complete.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
This being just a whitepaper, it should not be expected to be complete. 

@jlamy and @CharlesParisot  do you think these two additional features of XCPD are critical for the scope of the HIE-whitepaper?

**Comment by CharlesParisot** [comment]
John,

 

As stated before, I am blind to the context of this comment.

 

*	Do you speak of the Patient Location Service ?  ==> Critical to mention this actor and corresponding transaction.
*	Or do you speak of: Asynchronous Web Services Exchange Option and Deferred Response Option ? ==> I would definitively mention the Asynchronous Web Services Exchange Option.  You may omit the Deferred Response Option which is in a similar “vein” with a longer asynchronous time.

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : mercredi 10 février 2021 10:11
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Charles Parisot <charles@interopehealth.com>; Mention <mention@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] XCPD profile functionality seems to be missing (#91)

 

This being just a whitepaper, it should not be expected to be complete.

@jlamy <https://github.com/jlamy>  and @CharlesParisot <https://github.com/CharlesParisot>  do you think these two additional features of XCPD are critical for the scope of the HIE-whitepaper?

**Comment by ivan-zapreev-work** [comment]
Well, if the W.P. is about specifying the available profiles and their functionality/usefullness, then I would expect that part of the paper to be a high level but still complete description of the profiles. If not then the conclusions of the W.P. may be questioned as not being accurate. But this is indeed just my view on things, so I shall not insist on having this change.

**Comment by JohnMoehrke** [comment]
It is clear that we should remind the reader that we are only describing the common use of these profiles to support HIE, that the profiles are designed to be used in more use-cases and in more architectures. This kind of a statement could be at the top of the paper, and likely at the beginning of each chapter. It clearly is needed on the Patient Identity Management chapter. Would that be sufficient to cover these concerns about not covering the complete capabilities within each profile?

**Comment by CharlesParisot** [comment]
John,

 

I would cover these very briefly in notes where it comes into the flow HIE white paper flow.

Note: The PDQ profile also provides optional capabilities that can be mainly leveraged within Hospitals, such as …See ITI TF1, section xxxx.

 

Does that make sense.  A sort of advertising, but the note avoiding distracting the primary HIE reader.

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : jeudi 11 février 2021 08:02
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Charles Parisot <charles@interopehealth.com>; Mention <mention@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] XCPD profile functionality seems to be missing (#91)

 

It is clear that we should remind the reader that we are only describing the common use of these profiles to support HIE, that the profiles are designed to be used in more use-cases and in more architectures. This kind of a statement could be at the top of the paper, and likely at the beginning of each chapter. It clearly is needed on the Patient Identity Management chapter. Would that be sufficient to cover these concerns about not covering the complete capabilities within each profile?
