### ISSUE TITLE
PDQ Assumptions seems to be unclear

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#92]
**Section Number**
Section 5

**Issue**

In Table 5-1:

> 1. supports the access to a central registry of identities.

Which central registry of identities is it? Where is this assumption based on? I do not see a direct link to/citation of the PDQ IHE profile description. 

**Proposed Change** 

Please clearly indicate where this assumption comes from, preferably by citing the proper paragraph of the PDQ supplement.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
technically PDQ queries a registry. Most of the time PDQ is used to address a single registry that is responsible for truth. The PDQ specification allows clients to query multiple services, so it is true that in those cases there is no central registry but a distribution of registries. So the description is speaking of "common' use. 

We could easily remove the "central" word, but I am not sure that is overall an improvement.

**Comment by JohnMoehrke** [comment]
@BenLevy62 or @CharlesParisot do you have a comment or suggestion?

**Comment by CharlesParisot** [comment]
Github is such an abysmal tool for managing comments.  

This is a discussion on comment #92 says the subject line.  But in this message, I see no way to access the suggestion, and no way to access the original issue.

 

Sorry,

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : mercredi 10 février 2021 10:17
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Charles Parisot <charles@interopehealth.com>; Mention <mention@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] PDQ Assumptions seems to be unclear (#92)

 

@BenLevy62 <https://github.com/BenLevy62>  or @CharlesParisot <https://github.com/CharlesParisot>  do you have a comment or suggestion?

**Comment by CharlesParisot** [comment]
John,

 

I do not understand the response.

 

The PDQ Demographics Supplier is a single actor, so in that sense it is central for the several instances of the Patient Demographics Consumers.

 

Perhaps, you mean that the PDQ Demographics Supplier Actor may manage one or more patient identification domains and that a PDQ Demographics Query can be targeted at one of these patient identification domains, when multiple are supported.  Do you ?

 

In either case, there is no “distribution of registries”, no concept of federation of PDQ Demographics Supplier Actors in PDQ.

 

So “central” in PDQ may be used in contrast with XCPD, which allows Cross-Community Demographics Queries between peer federated communities.

 

Does that help ?

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : mercredi 10 février 2021 10:16
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] PDQ Assumptions seems to be unclear (#92)

 

technically PDQ queries a registry. Most of the time PDQ is used to address a single registry that is responsible for truth. The PDQ specification allows clients to query multiple services, so it is true that in those cases there is no central registry but a distribution of registries. So the description is speaking of "common' use.

We could easily remove the "central" word, but I am not sure that is overall an improvement.

**Comment by JohnMoehrke** [comment]
Good point Charles. The word "central" in PDQ is more a distinction from "federated" in XCPD. To indicate that PDQ (alone) is not supporting a federation. Yet if the server side does implement XCPD, then the PDQ query would result in an effective federated query as a two step. If this is the case, then we likely should just remove the word "central"
