### ISSUE TITLE
PMIR Assumption seems to be flawed

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#93]
**Section Number**
Section 5

**Issue**

In Table 5-1:

> 1. supports the distributed creation, access, update, and merge process of shared master patient identity.

There is a number of issues I see in this statement:
1. How is it "distributed" if there is one centralized Patient Identity Manager?
2. Patient identity linking/unlinking is missing.
3. The spec never calls "master patient identity" it "shared" master patient identity.

**Proposed Change** 

1. Explain what you mean with "distributed"
2. Add the missing "linking/unlinking"
3. Avoid using "shared"

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
agree with the need.

**Comment by JohnMoehrke** [comment]
for PMIR I now use the word "collaborative" rather than "distributed", and have inserted the word "shared" to "shared master identity"
