### ISSUE TITLE
PMIR Conditions seem to be flawed

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#94]
**Section Number**
Section 5

**Issue**

In Table 5-1:

> 1. Each deployment defines the policies to be followed by identity sources to ensure stability and quality of the master identities they create, update, and merge.
> 3. There is a mechanism to distribute all create, update, and merge actions to identity consumer actors, which have a duty to reflect these changes in their patient-specific information stores.

There is a number of issues I see in this statement:
1. In both of the Conditions the link/unlink is missing;
2. Regarding "which have a duty to reflect these changes in their patient-specific information stores." - I do not think it is stated anywhere in the PMIR spec that the consumers have this duty. Given that it is not related to interoperability one can not claim that such a duty exists;

**Proposed Change** 

1. Add the missing "link/unlink";
2. Double check with the PMIR spec and correct the text accordingly. I suggest just to remove this last piece of Condition as not true, or otherwise show where this condition comes from;

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
PMIR does NOT support link/unlink. PMIR is based on a community collaboratively managing a master identity.

PMIR does indicate as strongly as it can, given it has no clinical data in scope. It speaks to the intention of the recipient to adjust their data, and it hints at the fact that other profiles that do have scope over clinical data may add criteria as MHDS has.

So I think given that this is just a whitepaper, the text is okay. @ivan-zapreev-work can you confirm or suggest adjustments based on my statements?

**Comment by ivan-zapreev-work** [comment]
"PMIR does NOT support link/unlink. " not as an operation but it allows to request linked patient identifiers through ITI-83 thus it does support linking and unlinking, but then via a non-standard mechanism (as Patient.link). Also, PMIT supplement explicitly states that ITIT-93 is to be used for linking.

"which have a duty to reflect these changes" I am still not convinced one may state that there is a duty. If there was then it must have been part of the spec. But this comment is perhaps more about how it is formulated.
