### ISSUE TITLE
Unclearness in the PIX profile description

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#95]
**Section Number**
Section 5.1

**Issue**

The following description is unclear:

> The Patient Identity Cross-Reference PIX Profile supports the access to a central registry of cross-referenced identities, and the feed of identity updates from distributed identity domains. Most health information systems assign to each patient an identifier (usually a string of letters and/or numbers) that is unique to the patient within only that information system.

**Proposed Change** 

1. Do you mean to say that the identity updates are communicated from the identity domains to the central registry via dedicated feeds?
2. Why not to just place a PIX profile picture here, as that would help for understanding the text.
3. "usually a string of letters and/or numbers" - How is this important or relevant at this point and why do not you mention the assigning authority that is also typically part of such an identifier then? Please remove or clarify.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
I think all of these observations are beyond the scope of a whitepaper. The PIX profile exists, and we link often to it. The goal of the whitepaper is not to replicate the detail, but rather to provide a highlevel organization to the family of profiles.

Agree to remove the "usually a string of letters and/or numbers)" as unnecessary detail for a whitepaper.
