### ISSUE TITLE
An unclear sentence in the PIX profile description

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#96]
**Section Number**
Section 5.1

**Issue**

The following sentence is unclear:

> IHE utilizes the concept of Patient Identifier Domains which defines a domain of patient identifiers, like identifiers assigned within a PCP office, assigned by a single authority and an identifier for each assigning authority.

This sentence is not very clear and mixes the notion of the identification domain with the assigning authority where the latter is not explained or defined. Which makes the next sentence also unclear:

> For example, the PCP office identifier is unique within the assigning authority for the PCP.

Is it within the "assigning authority" or rather within the "PCP identification domain"?

**Proposed Change** 

Please clearly define the assigning authority and its relation to the identification domain.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
agreed
