### ISSUE TITLE
A seemingly unrelated text in PIX use example

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#97]
**Section Number**
Section 5.1

**Issue**

The following piece of text seems to be irrelevant:

> office, and that neither of those identifiers is equivalent to Garry Collin with an ID of 333 at a local Hospital.

This does not seem to be relevant because:
1. The local Hospital has even not been introduced before and even if it exists then it may not be part of the PIX deployment; 
2. Why would you like to know that neither of those identifiers are "equivalent to Garry Collin"?

**Proposed Change** 

Please clarify why this is relevant or remove.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
I can imagine reasons to know this, like avoiding incorrect merge... but if that is the point, then the point is deeper than a whitepaper should cover. Needs someone to look at it and decide if it is needed or not, and if needed to clarify it.
