### ISSUE TITLE
An unclear reference in the PIX profile example

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#98]
**Section Number**
Section 5.1

**Issue**

The following sentence seems unclear:

> This is known as a cross-reference that links the two patient identifiers for Gary Collins.

When you are saying "This", what exactly do you refer to?

**Proposed Change** 

Please clarify what is mean with "this".

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
correct needs clarity. Especially after the resolution of #97
