### ISSUE TITLE
Issues with Figure 5.1-1: Patient identifier cross-referencing

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#99]
**Section Number**
Section 5.1

**Issue**

I have a couple of issues with Figure 5.1-1: Patient identifier cross-referencing
1. The title of the figure does not seem to match with it content. There is little here about patent identifier cross referencing as it is a process and here we just have a deployment like picture without even clear identifications of the transaction responses.
2. You present the PIX profile without clearly introducing its roles and transactions. Then you provide some deployment as in Figure 5.1-1 and do not map the entities on the diagram with the profile roles as well as you do not map the interactions to the ITI transactions. This is misleading.

**Proposed Change** 

1. Improve the figure title
2. Present the PIX profile (as a picture)
3. Indicate which elements of Figure 5.1-1 actually play which PIX role and this interaction corresponds to which ITI transaction.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
I think you are seeking a level of detail that is deeper than intended in this whitepaper. I don't think these proposed changes should be done.

@ivan-zapreev-work please respond in light of the scope of this as a HIE whitepaper.

**Comment by ivan-zapreev-work** [comment]
Well, I disagree, my point is not that there are not sufficient details but rather that the provided information is not clear. The figure title is not descriptive and that it is hard to understand the presented figures and to align them with the text. I could not understand this even being busy with the PMIR, PIX and other Patient Identity Management related IHE profiles for the last 11 months.

**Comment by JohnMoehrke** [comment]
so it would seem you would prefer a diagram that shows sequence? This one is a static diagram showing the state of the system. The text is explaining that state.
The diagram style might be getting in the way. We tried this style some years ago, but since it is not the style we are using elsewhere it likely is not helpful to be this style.

should we draft up one using the style of the diagrams we used today?

**Comment by ivan-zapreev-work** [comment]
I remember one of my issues was that the entities presented on the diagrams were not mapped to the corresponding IHE profile actors and so the interactions between the systems were not mapped to the IHE profile transactions. Does this help?

As basically you provide an example and claim that it is PIX related whereas the PIX was not introduced and the example mapping to the PIX profile is not clear. So once I look at the picture I do not immediately see how is PIX being mapped to that.

**Comment by JohnMoehrke** [comment]
I have updated the diagram, the table, and the introduction to the table. Take a new look.

**Comment by ivan-zapreev-work** [comment]
This looks much clearer to me now, thank you so much for this improvement!
